# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheMovieApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheMovieApp

	pod 'Alamofire', '~> 4.7'
	pod 'RxSwift',    '~> 4.0'
    	pod 'RxCocoa',    '~> 4.0'
	pod 'SwiftyJSON', '~> 4.0'
	pod 'AlamofireObjectMapper', '~> 5.0'
	pod 'ObjectMapper', '~> 3.3'

  target 'TheMovieAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TheMovieAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
